<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-I2JN7UT" failures="1" tests="3" name="com.testProject.testcases.UserSignInTest" time="14.924" errors="0" timestamp="2024-08-08T17:49:42 BST" skipped="0">
  <testcase classname="com.testProject.testcases.UserSignInTest" name="userSignInTest" time="4.699">
    <failure message="Seems like the Username or password is wrong" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Seems like the Username or password is wrong
at org.testng.Assert.fail(Assert.java:111)
at com.testProject.testcases.UserSignInTest.userSignInTest(UserSignInTest.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[Clicked on Login Title link<br>
Typed in the Username<br>
Typed in the Password<br>
Clicked on Sign in button<br>
Welcome Title is not visible
Sign in not Successful, Please check username or Password<br>
<a target="_blank" href=C:\Users\Muhammad\Downloads\Selenium4AndOnward\DataDrivenOnly\target\Thu_Aug_08_17_49_36_BST_2024error.jpg>screenshot</a>]]>
    </system-out>
  </testcase> <!-- userSignInTest -->
  <testcase classname="com.testProject.testcases.UserSignInTest" name="userSignInTest" time="5.175">
    <system-out>
      <![CDATA[Clicked on Login Title link<br>
Typed in the Username<br>
Typed in the Password<br>
Clicked on Sign in button<br>
Yes, Welcome Title is visible<br>
Sign in Successful<br>]]>
    </system-out>
  </testcase> <!-- userSignInTest -->
  <testcase classname="com.testProject.testcases.UserSignInTest" name="userSignInTest" time="5.050">
    <system-out>
      <![CDATA[Clicked on Login Title link<br>
Typed in the Username<br>
Typed in the Password<br>
Clicked on Sign in button<br>
Yes, Welcome Title is visible<br>
Sign in Successful<br>]]>
    </system-out>
  </testcase> <!-- userSignInTest -->
  <system-out>
    <![CDATA[Clicked on Creat Account Button<br>
Typed the first Name<br>
Typed the Last Name<br>
Typed the email<br>
Typed the Password<br>
Confirm password by retyping<br>
Is the Welcome Element there? false
Account Already Exists,try another email<br>
<a target="_blank" href=C:\Users\Muhammad\Downloads\Selenium4AndOnward\DataDrivenOnly\target\Thu_Aug_08_17_49_26_BST_2024error.jpg>screenshot</a>
Clicked on Login Title link<br>
Typed in the Username<br>
Typed in the Password<br>
Clicked on Sign in button<br>
Yes, Welcome Title is visible<br>
Sign in Successful<br>
Clicked on Login Title link<br>
Typed in the Username<br>
Typed in the Password<br>
Clicked on Sign in button<br>
Welcome Title is not visible
Sign in not Successful, Please check username or Password<br>
<a target="_blank" href=C:\Users\Muhammad\Downloads\Selenium4AndOnward\DataDrivenOnly\target\Thu_Aug_08_17_49_36_BST_2024error.jpg>screenshot</a>
Clicked on Login Title link<br>
Typed in the Username<br>
Typed in the Password<br>
Clicked on Sign in button<br>
Yes, Welcome Title is visible<br>
Sign in Successful<br>]]>
  </system-out>
</testsuite> <!-- com.testProject.testcases.UserSignInTest -->
